import Head from 'next/head'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Blog from './components/blog'
import { Fade as Hamburger } from 'hamburger-react'
import { useState } from 'react'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [isOpen, setOpen] = useState(false)

 

  return (
   <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
      </Head>

      <nav className='nav-menu'>
        <Link href="/" className='logo'> MD TECH</Link>
        
        <Hamburger toggled={isOpen} toggle={setOpen} rounded  duration={0.8} color='#f1c40f' />
      <ul className={`list-menu ${isOpen ? 'is-open' : ''}`}>
          <li className='menu-item' >
            <Link href="/" className='link' >Início</Link>
          </li>
          <li className='menu-item'>
            <Link href="/"  className='link'>Blog</Link>
          </li>
          <li className='menu-item'>
            <Link href="/" className='link' >Sobre</Link>
          </li>
          <li className='menu-item'>
            <Link href="/" className='link' >Contato</Link>
          </li>
        </ul>
      </nav>
      </>
  )
}
